package wafdetect

import "strings"

// WAFSignature defines fingerprint patterns for a specific WAF
type WAFSignature struct {
	Name    string
	Vendor  string
	Headers map[string][]string // header name -> patterns to match in value
	Cookies []string            // cookie name patterns
	Body    []string            // response body patterns
	Codes   []int               // characteristic status codes from block pages

	// Pre-computed lowercase variants populated by init(); used by the
	// per-request hot loop to avoid ~216 redundant ToLower allocations per
	// target. Do NOT set these manually in the literals above.
	bodyLower    []string
	cookieLower  []string
	headersLower map[string][]string
}

// WAFDatabase contains all known WAF signatures
var WAFDatabase = []WAFSignature{
	// --- CDN / Cloud WAFs ---
	// Audit ER fix: refreshed 2024/2025 fingerprints — added Cf-Mitigated,
	// cf-chl* cookies, JS-challenge body marker, and Server-Timing cfL4;
	// __cfduid retained for legacy detection but no longer the only cookie.
	{
		Name: "Cloudflare", Vendor: "Cloudflare Inc.",
		Headers: map[string][]string{
			"Server":          {"cloudflare"},
			"Cf-Ray":          {""},
			"Cf-Cache-Status": {""},
			"Cf-Request-Id":   {""},
			"Cf-Mitigated":    {""},
			"Cf-Worker":       {""},
			"Server-Timing":   {"cfl4", "cfcache"},
		},
		Cookies: []string{"__cfduid", "cf_clearance", "__cf_bm", "cf_ob_info", "__cf_chl_rt_tk", "cf_chl_", "cf_chl_prog"},
		Body:    []string{"Attention Required! | Cloudflare", "cloudflare-nginx", "cf-error-details", "Cloudflare Ray ID", "DDoS protection by Cloudflare", "Just a moment...", "challenge-platform", "cf-chl-bypass", "Cloudflare to restrict access"},
		Codes:   []int{403, 503, 1020},
	},
	{
		Name: "AWS WAF (CloudFront)", Vendor: "Amazon Web Services",
		Headers: map[string][]string{
			"X-Amz-Cf-Id":       {""},
			"X-Amz-Cf-Pop":      {""},
			"X-Amzn-Waf-Action": {""},
			"X-Amzn-Requestid":  {""},
			"X-Amzn-Errortype":  {""},
			"X-Amzn-Trace-Id":   {""},
			"Server":            {"CloudFront", "awselb", "aws"},
			"X-Cache":           {"Error from cloudfront"},
		},
		Body:  []string{"ERROR: The request could not be satisfied", "Request blocked", "Generated by cloudfront", "awswaf.com"},
		Codes: []int{403},
	},
	{
		Name: "Akamai", Vendor: "Akamai Technologies",
		Headers: map[string][]string{
			"X-Akamai-Transformed":  {""},
			"Server":                {"AkamaiGHost", "AkamaiNetStorage"},
			"X-Akamai-Session-Info": {""},
			"X-Akamai-Request-Id":   {""},
			"Akamai-Grn":            {""},
		},
		Cookies: []string{"akamai_generated", "AkamaiEdge", "akacd_", "ak_bmsc", "bm_sv", "bm_sz", "_abck"},
		Body:    []string{"Access Denied", "Reference&#32;&#35;", "akamai.com/apps/abuse-feedback", "You don't have permission to access", "Reference #"},
		Codes:   []int{403},
	},
	{
		Name: "Sucuri", Vendor: "Sucuri Inc.",
		Headers: map[string][]string{
			"X-Sucuri-ID":    {""},
			"X-Sucuri-Cache": {""},
			"Server":         {"Sucuri", "Sucuri/Cloudproxy"},
		},
		Cookies: []string{"sucuri_cloudproxy_uuid"},
		Body:    []string{"Access Denied - Sucuri Website Firewall", "sucuri.net/privacy-policy", "Sucuri WebSite Firewall", "cloudproxy@sucuri.net"},
		Codes:   []int{403},
	},
	{
		Name: "Imperva (Incapsula)", Vendor: "Imperva",
		Headers: map[string][]string{
			"X-Iinfo": {""},
			"X-CDN":   {"Imperva", "Incapsula"},
		},
		Cookies: []string{"incap_ses_", "visid_incap_", "nlbi_", "__utmvc"},
		Body:    []string{"Powered by Incapsula", "Incapsula incident ID", "_Incapsula_Resource", "Request unsuccessful. Incapsula"},
		Codes:   []int{403},
	},

	// --- Enterprise WAFs ---
	{
		Name: "F5 BIG-IP ASM", Vendor: "F5 Networks",
		Headers: map[string][]string{
			"X-WA-Info": {""},
			"Server":    {"BigIP", "BIG-IP", "BIGIP"},
		},
		Cookies: []string{"TS", "BIGipServer", "F5_ST", "f5_cspm", "MRHSession"},
		Body:    []string{"The requested URL was rejected", "Please consult with your administrator", "support ID is"},
	},
	{
		Name: "Barracuda", Vendor: "Barracuda Networks",
		Headers: map[string][]string{
			"Server": {"Barracuda"},
		},
		Cookies: []string{"barra_counter_session", "BNI__BARRAESSION"},
		Body:    []string{"Barracuda Web Application Firewall", "You have been blocked", "barracuda.com"},
	},
	{
		Name: "Fortinet FortiWeb", Vendor: "Fortinet",
		Headers: map[string][]string{
			"Server": {"FortiWeb"},
		},
		Cookies: []string{"FORTIWAFSID", "cookiesession1"},
		Body:    []string{"FortiWeb", ".fwb_", "FortiGuard"},
	},
	{
		Name: "Citrix NetScaler AppFirewall", Vendor: "Citrix",
		Headers: map[string][]string{
			"Via":        {"NS-CACHE"},
			"Cneonction": {""},
			"X-Ns-Cache": {""},
			"Conn":       {""},
			"X-CIAS-Ver": {""},
		},
		Cookies: []string{"ns_af", "citrix_ns_id", "NSC_"},
		Body:    []string{"ns_af", "Citrix Access Gateway", "NetScaler"},
	},
	{
		Name: "ModSecurity", Vendor: "Trustwave / OWASP",
		Headers: map[string][]string{
			"Server": {"Mod_Security", "NOYB", "mod_security"},
		},
		Body:  []string{"ModSecurity", "Mod_Security", "This error was generated by Mod_Security", "NOYB", "mod_security", "rules of the mod_security"},
		Codes: []int{403, 406},
	},

	// --- Cloud Platform WAFs ---
	{
		Name: "Google Cloud Armor", Vendor: "Google Cloud",
		Headers: map[string][]string{
			"Server":  {"Google Frontend"},
			"X-Goog-": {""},
		},
		Body: []string{"Error 403 (Forbidden)", "Your client does not have permission"},
	},
	{
		Name: "Azure Front Door / Application Gateway", Vendor: "Microsoft Azure",
		Headers: map[string][]string{
			"X-Azure-Ref":       {""},
			"X-Ms-Forbidden-Ip": {""},
			"X-Msedge-Ref":      {""},
		},
		Body: []string{"Azure Application Gateway", "This website is using a security service", "Microsoft-Azure-Application-Gateway"},
	},

	// --- Other WAFs ---
	{
		Name: "Wordfence", Vendor: "Defiant Inc.",
		Body: []string{"Generated by Wordfence", "wfVt=", "wordfence", "This response was generated by Wordfence"},
	},
	{
		Name: "DenyAll", Vendor: "DenyAll",
		Headers: map[string][]string{
			"Server": {"DenyAll"},
		},
		Cookies: []string{"sessioncookie", "da"},
	},
	{
		Name: "Comodo WAF", Vendor: "Comodo",
		Headers: map[string][]string{
			"Server": {"Protected by COMODO"},
		},
	},
	{
		Name: "Wallarm", Vendor: "Wallarm",
		Headers: map[string][]string{
			"Server": {"nginx-wallarm"},
		},
	},
	{
		Name: "DDoS-Guard", Vendor: "DDoS-Guard",
		Headers: map[string][]string{
			"Server": {"ddos-guard"},
		},
		Cookies: []string{"__ddg1", "__ddg2", "__ddgid", "__ddgmark"},
	},
	{
		Name: "StackPath", Vendor: "StackPath",
		Headers: map[string][]string{
			"X-Sp-Url": {""},
			"X-Sp-Waf": {""},
		},
		Cookies: []string{"sp_waf_"},
	},
	{
		Name: "Varnish / Section.io", Vendor: "Varnish Software",
		Headers: map[string][]string{
			"X-Varnish":       {""},
			"Via":             {"varnish"},
			"X-Section-Io-Id": {""},
		},
	},
	{
		Name: "Reblaze", Vendor: "Reblaze",
		Headers: map[string][]string{
			"Server": {"Reblaze Secure Web Gateway"},
		},
		Cookies: []string{"rbzid", "rbzsessionid"},
	},
	{
		Name: "SonicWall", Vendor: "SonicWall",
		Headers: map[string][]string{
			"Server": {"SonicWALL"},
		},
		Body: []string{"This request is blocked by the SonicWALL", "Web Site Blocked"},
	},
	{
		Name: "Safe3", Vendor: "Safe3",
		Headers: map[string][]string{
			"X-Powered-By": {"Safe3WAF"},
			"Server":       {"Safe3"},
		},
	},
	{
		Name: "PowerCDN", Vendor: "PowerCDN",
		Headers: map[string][]string{
			"X-Cache":    {""},
			"X-PowerCDN": {""},
			"Server":     {"PowerCDN"},
		},
	},
	// Audit ER fix: modern edge platforms added to close the wafw00f gap.
	{
		Name: "Vercel", Vendor: "Vercel Inc.",
		Headers: map[string][]string{
			"Server":            {"Vercel"},
			"X-Vercel-Id":       {""},
			"X-Vercel-Cache":    {""},
			"X-Vercel-Trace":    {""},
			"X-Vercel-Deployment-Url": {""},
		},
	},
	{
		Name: "Fastly", Vendor: "Fastly Inc.",
		Headers: map[string][]string{
			"Fastly-Ff":     {""},
			"Fastly-Debug-Digest": {""},
			"X-Served-By":   {"cache-"},
			"X-Fastly-Request-Id": {""},
			"X-Timer":       {""},
			"Via":           {"varnish"},
		},
		Body: []string{"Fastly error", "Request-ID:"},
	},
	{
		Name: "AWS WAF (Standalone)", Vendor: "Amazon Web Services",
		Headers: map[string][]string{
			"X-Amzn-Requestid":  {""},
			"X-Amzn-Errortype":  {""},
			"X-Amzn-Trace-Id":   {""},
			"X-Amzn-Waf-Action": {""},
		},
		Body:  []string{"awswaf.com", "Request blocked by AWS WAF", "AWS WAF"},
		Codes: []int{403},
	},
	{
		Name: "Alibaba Cloud WAF", Vendor: "Alibaba Cloud",
		Headers: map[string][]string{
			"Server": {"Tengine", "AliyunOSS"},
		},
		Cookies: []string{"aliyungf_tc", "acw_tc", "acw_sc__v2"},
		Body:    []string{"errors.aliyun.com", "yundun.aliyun.com"},
	},
	{
		Name: "Tencent Cloud WAF", Vendor: "Tencent Cloud",
		Headers: map[string][]string{
			"Server": {"waf-cloud", "sc waf"},
		},
		Body: []string{"waf.tencentcloud.com"},
	},
}

// matchHeader checks if a header value contains any of the patterns.
// patterns is expected to already be lowercased (see init() below) so callers
// can lowercase the value once and skip per-pattern allocations.
func matchHeader(headerValue string, patterns []string) bool {
	lower := strings.ToLower(headerValue)
	for _, p := range patterns {
		if p == "" {
			return true // empty pattern = header existence check
		}
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

// init pre-computes lowercase versions of every signature's body, cookie, and
// header patterns. This removes ~216 strings.ToLower(pattern) calls per target
// from the wafdetect hot loop (24 signatures × up to 9 probes).
func init() {
	for i := range WAFDatabase {
		sig := &WAFDatabase[i]

		if len(sig.Body) > 0 {
			sig.bodyLower = make([]string, len(sig.Body))
			for j, p := range sig.Body {
				sig.bodyLower[j] = strings.ToLower(p)
			}
		}
		if len(sig.Cookies) > 0 {
			sig.cookieLower = make([]string, len(sig.Cookies))
			for j, p := range sig.Cookies {
				sig.cookieLower[j] = strings.ToLower(p)
			}
		}
		if len(sig.Headers) > 0 {
			sig.headersLower = make(map[string][]string, len(sig.Headers))
			for hdr, patterns := range sig.Headers {
				lp := make([]string, len(patterns))
				for j, p := range patterns {
					lp[j] = strings.ToLower(p)
				}
				sig.headersLower[hdr] = lp
			}
		}
	}
}
