package handlers

import (
	"archive/zip"
	"bytes"
	"fmt"
	"net/http"
	"strings"

	"github.com/go-pdf/fpdf"
)

// Per-vulnerability report export (PDF + DOCX, TR + EN). Page 1 is a
// standardized details table (the report fields + the stable vuln ID); page 2
// is the PoC. Scanner-captured data wins; the class knowledge base (vuln_kb.go)
// fills the narrative blanks. See the Vulnerabilities page for the trigger.

const fontDir = "web/static/fonts"

// VulnReport is one fully-resolved, language-selected vulnerability ready to
// render. Every field is a display string.
type VulnReport struct {
	ID            string
	Name          string
	Severity      string
	SevRank       int
	CVSS          string // "score — vector"
	CVECWE        string // "CVE-… / CWE-…"
	DomainIP      string
	PortProto     string
	Asset         string
	Preconditions string
	Description   string
	Impact        string
	Remediation   string
	PoC           string
}

// reportLabels holds the page-1 field labels + section headings per language.
type reportLabelSet struct {
	Title         string
	ID            string
	Name          string
	Severity      string
	CVSS          string
	CVECWE        string
	DomainIP      string
	PortProto     string
	Asset         string
	Preconditions string
	Description   string
	Impact        string
	Remediation   string
	PoC           string
	NoPoC         string
	ReqLabel      string
	RespLabel     string
	EvLabel       string
	Generated     string
}

var reportLabels = map[string]reportLabelSet{
	"tr": {
		Title:         "Zafiyet Raporu",
		ID:            "Zafiyet ID",
		Name:          "Zafiyet Adı",
		Severity:      "Önem Derecesi",
		CVSS:          "CVSS v3.1 Skoru / Vektörü",
		CVECWE:        "CVE / CWE",
		DomainIP:      "Alan Adı / IPv4",
		PortProto:     "Port / Protokol",
		Asset:         "Etkilenen Varlık",
		Preconditions: "Ön Koşullar",
		Description:   "Açıklaması",
		Impact:        "Etkileri",
		Remediation:   "Çözüm Önerileri",
		PoC:           "Kavram Kanıtı (PoC)",
		NoPoC:         "Bu bulgu için otomatik yakalanmış ham istek/yanıt bulunmuyor. Bulguyu, etkilenen varlık üzerinde açıklamada belirtilen adımları izleyerek doğrulayın.",
		ReqLabel:      "İSTEK",
		RespLabel:     "YANIT",
		EvLabel:       "Kanıt",
		Generated:     "scaNNer tarafından oluşturuldu",
	},
	"en": {
		Title:         "Vulnerability Report",
		ID:            "Vulnerability ID",
		Name:          "Vulnerability Name",
		Severity:      "Severity",
		CVSS:          "CVSS v3.1 Score / Vector",
		CVECWE:        "CVE / CWE",
		DomainIP:      "Domain / IPv4",
		PortProto:     "Port / Protocol",
		Asset:         "Affected Asset",
		Preconditions: "Preconditions",
		Description:   "Description",
		Impact:        "Impact",
		Remediation:   "Remediation",
		PoC:           "Proof of Concept (PoC)",
		NoPoC:         "No raw request/response was automatically captured for this finding. Reproduce it against the affected asset following the steps in the description.",
		ReqLabel:      "REQUEST",
		RespLabel:     "RESPONSE",
		EvLabel:       "Evidence",
		Generated:     "Generated by scaNNer",
	},
}

func labelsFor(lang string) reportLabelSet {
	if strings.EqualFold(lang, "en") {
		return reportLabels["en"]
	}
	return reportLabels["tr"]
}

// severityLabel localizes the severity for display.
func severityLabel(sevRank int, lang string) string {
	en := strings.EqualFold(lang, "en")
	switch sevRank {
	case 4:
		if en {
			return "Critical"
		}
		return "Kritik"
	case 3:
		if en {
			return "High"
		}
		return "Yüksek"
	case 2:
		if en {
			return "Medium"
		}
		return "Orta"
	case 1:
		if en {
			return "Low"
		}
		return "Düşük"
	}
	if en {
		return "Info"
	}
	return "Bilgi"
}

// severityRGB returns the report color for a severity rank.
func severityRGB(sevRank int) (int, int, int) {
	switch sevRank {
	case 4:
		return 0xB9, 0x1C, 0x1C
	case 3:
		return 0xEA, 0x58, 0x0C
	case 2:
		return 0xCA, 0x8A, 0x04
	case 1:
		return 0x25, 0x63, 0xEB
	}
	return 0x6B, 0x72, 0x80
}

// buildVulnReport resolves a GlobalVuln + KB into a language-selected report.
func buildVulnReport(v GlobalVuln, lang string) VulnReport {
	class := classifyVuln(v.Module, v.Title, len(v.CVEs) > 0)
	kb := kbTextFor(class, lang)

	// CVSS: score (captured) + vector (captured else KB).
	vector := firstNonEmpty(v.CVSSVector, kb.CVSSVector)
	var cvss string
	switch {
	case v.CVSSScore != "" && vector != "":
		cvss = v.CVSSScore + " — " + vector
	case v.CVSSScore != "":
		cvss = v.CVSSScore
	case vector != "":
		cvss = vector
	}

	// CVE / CWE.
	cwe := kb.CWE
	if len(v.CWEs) > 0 {
		cwe = strings.Join(v.CWEs, ", ")
	}
	cve := strings.Join(v.CVEs, ", ")
	var cvecwe string
	switch {
	case cve != "" && cwe != "":
		cvecwe = cve + " / " + cwe
	case cve != "":
		cvecwe = cve
	case cwe != "":
		cvecwe = cwe
	}

	portProto := ""
	if v.Port != "" {
		portProto = v.Port
		if v.Protocol != "" {
			portProto += "/" + v.Protocol
		}
	}

	// Narrative prose must match the report language. Scanner-captured
	// Description/Remediation are ALWAYS English (tool output), so in Turkish
	// mode we use the KB's Turkish text and never leak English prose; in
	// English mode we prefer the more specific captured text, then the KB.
	// (Preconditions/Impact are never captured — always KB, already localized.
	// Evidence/request/response in the PoC stay verbatim: they're raw technical
	// artifacts, not translatable prose.)
	name := v.Title
	desc, rem := kb.Description, kb.Remediation
	if strings.EqualFold(lang, "en") {
		desc = firstNonEmpty(v.Description, kb.Description)
		rem = firstNonEmpty(v.Remediation, kb.Remediation)
	} else {
		// TR: translate recognized TLS/certificate finding titles (and their
		// descriptions) so the report reads fully in Turkish instead of leaking
		// English titles like "No Modern TLS".
		if trTitle, trDesc := tlsTitleTR(v.Title); trTitle != "" {
			name = trTitle
			if trDesc != "" {
				desc = trDesc
			}
		}
	}

	// TLS findings carry no HTTP request/response. Prefer the real tool run the
	// sslscan module captured (exact command + its console output); else fall
	// back to a synthesized command-based PoC rather than "no PoC captured".
	poc := buildPoC(v, lang)
	if class == "weak-tls" {
		if strings.TrimSpace(v.PoCCommand) != "" || strings.TrimSpace(v.PoCOutput) != "" {
			poc = tlsPoCReal(v, lang)
		} else if strings.TrimSpace(v.RawRequest) == "" && strings.TrimSpace(v.RawResponse) == "" {
			poc = tlsPoC(v, lang)
		}
	}

	return VulnReport{
		ID:            v.ID,
		Name:          name,
		Severity:      severityLabel(v.SevRank, lang),
		SevRank:       v.SevRank,
		CVSS:          cvss,
		CVECWE:        cvecwe,
		DomainIP:      normalizeAsset(v.Host),
		PortProto:     portProto,
		Asset:         v.Host,
		Preconditions: kb.Preconditions, // never captured — always KB
		Description:   desc,
		Impact:        kb.Impact, // never captured — always KB
		Remediation:   rem,
		PoC:           poc,
	}
}

func firstNonEmpty(a, b string) string {
	if strings.TrimSpace(a) != "" {
		return a
	}
	return b
}

// buildPoC assembles the page-2 proof-of-concept from captured request/response
// and evidence, falling back to a KB reproduction note.
func buildPoC(v GlobalVuln, lang string) string {
	l := labelsFor(lang)
	var b strings.Builder
	if strings.TrimSpace(v.RawRequest) != "" {
		b.WriteString(l.ReqLabel + ":\n" + strings.TrimRight(v.RawRequest, "\n") + "\n\n")
	}
	if strings.TrimSpace(v.RawResponse) != "" {
		b.WriteString(l.RespLabel + ":\n" + strings.TrimRight(v.RawResponse, "\n") + "\n\n")
	}
	if strings.TrimSpace(v.Evidence) != "" {
		b.WriteString(l.EvLabel + ":\n" + strings.TrimRight(v.Evidence, "\n") + "\n")
	}
	if strings.TrimSpace(b.String()) == "" {
		return l.NoPoC
	}
	return strings.TrimRight(b.String(), "\n")
}

// identifierRows are the short, scalar page-1 fields shown as a 2-column table
// (each value is at most a few lines, so the table paginates safely).
func identifierRows(rep VulnReport, lang string) [][2]string {
	l := labelsFor(lang)
	return [][2]string{
		{l.ID, rep.ID},
		{l.Name, rep.Name},
		{l.Severity, rep.Severity},
		{l.CVSS, rep.CVSS},
		{l.CVECWE, rep.CVECWE},
		{l.DomainIP, rep.DomainIP},
		{l.PortProto, rep.PortProto},
		{l.Asset, rep.Asset},
	}
}

// narrativeSections are the prose page-1 fields rendered as titled blocks below
// the table, so a long value flows/paginates naturally instead of overflowing a
// fixed-height table cell.
func narrativeSections(rep VulnReport, lang string) [][2]string {
	l := labelsFor(lang)
	return [][2]string{
		{l.Preconditions, rep.Preconditions},
		{l.Description, rep.Description},
		{l.Impact, rep.Impact},
		{l.Remediation, rep.Remediation},
	}
}

// pdfSafe makes text safe for go-pdf/fpdf's UTF-8 renderer: it repairs invalid
// UTF-8, drops C0/C1 control chars (except tab/LF/CR), and replaces code points
// above the BMP (> U+FFFF) with U+FFFD. fpdf v0.9.0 errors on non-BMP runes,
// which would abort the entire PDF — so a single emoji/CJK-supplementary rune in
// one finding must not fail a bulk export.
func pdfSafe(s string) string {
	s = strings.ToValidUTF8(s, "")
	return strings.Map(func(r rune) rune {
		switch {
		case r == '\t' || r == '\n' || r == '\r':
			return r
		case r < 0x20, r >= 0x7F && r <= 0x9F:
			return -1
		case r > 0xFFFF:
			return '�'
		}
		return r
	}, s)
}

// sanitizeReportForPDF runs pdfSafe over every rendered field of a report.
func sanitizeReportForPDF(rep VulnReport) VulnReport {
	rep.ID = pdfSafe(rep.ID)
	rep.Name = pdfSafe(rep.Name)
	rep.Severity = pdfSafe(rep.Severity)
	rep.CVSS = pdfSafe(rep.CVSS)
	rep.CVECWE = pdfSafe(rep.CVECWE)
	rep.DomainIP = pdfSafe(rep.DomainIP)
	rep.PortProto = pdfSafe(rep.PortProto)
	rep.Asset = pdfSafe(rep.Asset)
	rep.Preconditions = pdfSafe(rep.Preconditions)
	rep.Description = pdfSafe(rep.Description)
	rep.Impact = pdfSafe(rep.Impact)
	rep.Remediation = pdfSafe(rep.Remediation)
	rep.PoC = pdfSafe(rep.PoC)
	return rep
}

// ---- PDF renderer (fpdf + bundled DejaVu UTF-8 fonts for Turkish) ----

func buildVulnPDF(reports []VulnReport, lang string) ([]byte, error) {
	l := labelsFor(lang)
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddUTF8Font("DejaVu", "", fontDir+"/DejaVuSans.ttf")
	pdf.AddUTF8Font("DejaVu", "B", fontDir+"/DejaVuSans-Bold.ttf")
	pdf.AddUTF8Font("Mono", "", fontDir+"/DejaVuSansMono.ttf")
	pdf.SetAutoPageBreak(true, 15)

	const contentW = 190.0 // A4 width 210 - 2*10 margins

	for _, rep := range reports {
		rep = sanitizeReportForPDF(rep) // fpdf rejects code points > U+FFFF

		// ---- Page 1: details ----
		pdf.AddPage()
		pdf.SetFont("DejaVu", "B", 15)
		pdf.SetTextColor(17, 24, 39)
		pdf.MultiCell(0, 8, l.Title, "", "L", false)
		pdf.SetFont("DejaVu", "", 9)
		pdf.SetTextColor(107, 114, 128)
		pdf.MultiCell(0, 5, rep.ID+"  ·  "+rep.Name, "", "L", false)
		pdf.Ln(3)

		// Identifier table: a shaded left label column + value column, height
		// per row = the taller of the two wrapped cells, with a bottom rule.
		// No cell borders (which fpdf can't keep aligned across differing cell
		// heights); the left-column fill + rules read as a clean table. Values
		// here are short (a few lines) so a row always fits a page.
		const labelW = 50.0
		const valueW = contentW - labelW
		const lh = 4.6
		for _, row := range identifierRows(rep, lang) {
			label, value := row[0], row[1]
			if strings.TrimSpace(value) == "" {
				value = "—"
			}
			pdf.SetFont("DejaVu", "B", 8)
			nLabel := len(pdf.SplitLines([]byte(label), labelW-3))
			pdf.SetFont("DejaVu", "", 9)
			nValue := len(pdf.SplitLines([]byte(value), valueW-3))
			n := nLabel
			if nValue > n {
				n = nValue
			}
			if n < 1 {
				n = 1
			}
			rowH := float64(n)*lh + 1.6
			if pdf.GetY()+rowH > 285 {
				pdf.AddPage()
			}
			x, y := pdf.GetX(), pdf.GetY()
			// label column background
			pdf.SetFillColor(243, 244, 246)
			pdf.Rect(x, y, labelW, rowH, "F")
			pdf.SetFont("DejaVu", "B", 8)
			pdf.SetTextColor(75, 85, 99)
			pdf.SetXY(x+1.5, y+1.4)
			pdf.MultiCell(labelW-3, lh, label, "", "L", false)
			// value column
			if label == l.Severity {
				r, g, b := severityRGB(rep.SevRank)
				pdf.SetTextColor(r, g, b)
				pdf.SetFont("DejaVu", "B", 9)
			} else {
				pdf.SetTextColor(17, 24, 39)
				pdf.SetFont("DejaVu", "", 9)
			}
			pdf.SetXY(x+labelW+2, y+1.4)
			pdf.MultiCell(valueW-3, lh, value, "", "L", false)
			// bottom rule + advance
			pdf.SetDrawColor(226, 232, 240)
			pdf.Line(x, y+rowH, x+contentW, y+rowH)
			pdf.SetXY(x, y+rowH)
		}
		pdf.Ln(3)

		// Narrative sections: title + flowing block (auto-paginates).
		for _, sec := range narrativeSections(rep, lang) {
			title, body := sec[0], sec[1]
			if strings.TrimSpace(body) == "" {
				body = "—"
			}
			if pdf.GetY()+12 > 285 {
				pdf.AddPage()
			}
			pdf.SetFont("DejaVu", "B", 10)
			pdf.SetTextColor(31, 41, 55)
			pdf.MultiCell(0, 5.5, title, "", "L", false)
			pdf.SetFont("DejaVu", "", 9)
			pdf.SetTextColor(31, 41, 55)
			pdf.MultiCell(contentW, 5, body, "", "L", false)
			pdf.Ln(2.5)
		}

		// ---- Page 2: PoC ----
		pdf.AddPage()
		pdf.SetFont("DejaVu", "B", 13)
		pdf.SetTextColor(17, 24, 39)
		pdf.MultiCell(0, 7, l.PoC, "", "L", false)
		pdf.SetFont("DejaVu", "", 8)
		pdf.SetTextColor(107, 114, 128)
		pdf.MultiCell(0, 5, rep.ID+"  ·  "+rep.Name, "", "L", false)
		pdf.Ln(2)
		pdf.SetFont("Mono", "", 7)
		pdf.SetTextColor(20, 20, 20)
		pdf.SetFillColor(247, 247, 247)
		pdf.MultiCell(0, 4, rep.PoC, "1", "L", true)
	}

	if err := pdf.Error(); err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// exportVulnPDF streams a single combined PDF of the reports.
func (h *Handler) exportVulnPDF(w http.ResponseWriter, reports []VulnReport, lang, fnameBase string) {
	data, err := buildVulnPDF(reports, lang)
	if err != nil {
		http.Error(w, "PDF generation failed: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s.pdf", fnameBase))
	_, _ = w.Write(data)
}

// ---- DOCX renderer ----

func buildVulnDOCX(reports []VulnReport, lang string) ([]byte, error) {
	l := labelsFor(lang)
	d := &docxBuilder{}
	for i, rep := range reports {
		if i > 0 {
			d.pageBreak()
		}
		// Page 1: identifier table, then narrative sections.
		d.heading(l.Title, 16, "111827")
		d.para(rep.ID + "  ·  " + rep.Name)
		d.kvTable(identifierRows(rep, lang))
		for _, sec := range narrativeSections(rep, lang) {
			body := sec[1]
			if strings.TrimSpace(body) == "" {
				body = "—"
			}
			d.heading(sec[0], 11, "374151")
			d.para(body)
		}
		// Page 2
		d.pageBreak()
		r, g, b := severityRGB(rep.SevRank)
		d.heading(l.PoC, 14, fmt.Sprintf("%02X%02X%02X", r, g, b))
		d.para(rep.ID + "  ·  " + rep.Name)
		for _, line := range strings.Split(rep.PoC, "\n") {
			d.mono(line)
		}
	}
	return d.bytesOut()
}

// exportVulnDOCX streams a single combined DOCX of the reports.
func (h *Handler) exportVulnDOCX(w http.ResponseWriter, reports []VulnReport, lang, fnameBase string) {
	out, err := buildVulnDOCX(reports, lang)
	if err != nil {
		http.Error(w, "DOCX generation failed: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s.docx", fnameBase))
	_, _ = w.Write(out)
}

// exportVulnZip streams a ZIP of one file PER vulnerability (the "separate
// files" bulk option) instead of one combined document.
func (h *Handler) exportVulnZip(w http.ResponseWriter, selected []GlobalVuln, format, lang, fnameBase string) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, v := range selected {
		rep := buildVulnReport(v, lang)
		var data []byte
		var err error
		ext := "pdf"
		if format == "docx" {
			ext = "docx"
			data, err = buildVulnDOCX([]VulnReport{rep}, lang)
		} else {
			data, err = buildVulnPDF([]VulnReport{rep}, lang)
		}
		if err != nil {
			continue // skip a vuln that failed to render rather than abort the batch
		}
		fw, err := zw.Create(vulnFileBase(v) + "." + ext)
		if err != nil {
			continue
		}
		_, _ = fw.Write(data)
	}
	if err := zw.Close(); err != nil {
		http.Error(w, "ZIP generation failed: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s.zip", fnameBase))
	_, _ = w.Write(buf.Bytes())
}

// vulnFileBase builds the per-vulnerability export filename stem in the shape
// the operator asked for: {affected asset}_{scan id}_{vulnerability name}.
// Each component is sanitized to a filesystem/HTTP-header-safe token and empty
// components collapse, so the join never yields a leading/trailing/double
// separator. The scan id uses the short 8-char form the UI shows ("Scan
// #0f636c1d"). Falls back to the vuln's own id if every component is empty.
func vulnFileBase(v GlobalVuln) string {
	scanID := v.ScanID
	if len(scanID) > 8 {
		scanID = scanID[:8]
	}
	parts := make([]string, 0, 3)
	for _, p := range []string{v.Host, scanID, v.Title} {
		if s := fsSafeToken(p); s != "" {
			parts = append(parts, s)
		}
	}
	base := strings.Join(parts, "_")
	if base == "" {
		base = "vuln_" + fsSafeToken(v.ID)
	}
	if len(base) > 150 { // stay well under filesystem + header length limits
		base = strings.Trim(base[:150], "_-.")
	}
	return base
}

// fsSafeToken reduces an arbitrary string (host, title, id) to a safe filename
// token: ASCII letters/digits/dot/dash are kept, every other rune becomes an
// underscore, runs of underscores collapse, and the result is trimmed of
// leading/trailing separators.
func fsSafeToken(s string) string {
	s = strings.TrimSpace(s)
	var b strings.Builder
	prevUnderscore := false
	for _, r := range s {
		keep := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '.' || r == '-'
		if keep {
			b.WriteRune(r)
			prevUnderscore = false
		} else if !prevUnderscore {
			b.WriteByte('_')
			prevUnderscore = true
		}
	}
	return strings.Trim(b.String(), "_-.")
}

// ---- Export handler ----

// VulnDetail renders one vulnerability's detail-drawer fragment (report +
// PoC), fetched lazily by the Vulnerabilities page when a row is expanded. The
// page ships with empty drawers so it stays small; this endpoint does the
// per-vuln buildVulnReport work only on demand.
func (h *Handler) VulnDetail(w http.ResponseWriter, r *http.Request) {
	ws := h.activeWorkspace(r)
	if ws == nil {
		http.Error(w, "no active workspace", http.StatusBadRequest)
		return
	}
	id := r.URL.Query().Get("id")
	liteScans, _ := h.db.ListScansLite(ws.ID, "")
	vulns, _ := h.getVulnIndex(ws.ID, liteScans)
	for i := range vulns {
		if vulns[i].ID == id {
			h.render(w, "vuln_detail_inner", vulns[i])
			return
		}
	}
	http.NotFound(w, r)
}

// VulnExport serves a per-vulnerability (or multi/bulk) report in PDF or DOCX,
// TR or EN. Selection (first match wins): ids=<SCN,SCN,…> (checkbox multi-
// select, via GET or POST form) → all=1 (filtered bulk, honoring sev/module/q)
// → id=<SCN> (single). format=pdf|docx; lang=tr|en.
func (h *Handler) VulnExport(w http.ResponseWriter, r *http.Request) {
	ws := h.activeWorkspace(r)
	if ws == nil {
		http.Error(w, "no active workspace", http.StatusBadRequest)
		return
	}
	liteScans, _ := h.db.ListScansLite(ws.ID, "")
	vulns, _ := h.getVulnIndex(ws.ID, liteScans)

	// FormValue reads either the query string (GET links: per-row id, all=1)
	// or a POST body (the "Export Selected" form, whose ids list can be long).
	_ = r.ParseForm()
	get := r.FormValue
	format := strings.ToLower(get("format"))
	if format != "docx" {
		format = "pdf"
	}
	lang := strings.ToLower(get("lang"))
	if lang != "en" {
		lang = "tr"
	}

	var selected []GlobalVuln
	fnameBase := "vulnerability"
	switch {
	case strings.TrimSpace(get("ids")) != "":
		// Multi-select: a comma-separated set of SCN ids. Emit in the page's
		// severity order (vulns is already sorted), not the click order.
		want := map[string]bool{}
		for _, id := range strings.Split(get("ids"), ",") {
			if id = strings.TrimSpace(id); id != "" {
				want[id] = true
			}
		}
		for _, v := range vulns {
			if want[v.ID] {
				selected = append(selected, v)
			}
		}
		fnameBase = fmt.Sprintf("vulnerabilities_%d", len(selected))
	case get("all") == "1":
		// sev may be a comma-separated set of ranks (multi-select filter), e.g. "4,3".
		sevSet := map[string]bool{}
		for _, s := range strings.Split(get("sev"), ",") {
			if s = strings.TrimSpace(s); s != "" {
				sevSet[s] = true
			}
		}
		mod := get("module")
		needle := strings.ToLower(strings.TrimSpace(get("q")))
		for _, v := range vulns {
			if len(sevSet) > 0 && !sevSet[itoa(v.SevRank)] {
				continue
			}
			if mod != "" && v.Module != mod {
				continue
			}
			if needle != "" {
				hay := strings.ToLower(v.Host + " " + v.Title + " " + v.Module + " " + strings.Join(v.CVEs, " "))
				if !strings.Contains(hay, needle) {
					continue
				}
			}
			selected = append(selected, v)
		}
		fnameBase = fmt.Sprintf("vulnerabilities_%d", len(selected))
	default:
		id := get("id")
		for _, v := range vulns {
			if v.ID == id {
				selected = append(selected, v)
				break
			}
		}
		if len(selected) == 1 {
			fnameBase = vulnFileBase(selected[0])
		}
	}

	if len(selected) == 0 {
		http.Error(w, "vulnerability not found (the index may still be building — reload the Vulnerabilities page and retry)", http.StatusNotFound)
		return
	}

	// separate=1 → one file per vulnerability, zipped (the "ayrı ayrı" bulk
	// option) instead of a single combined document.
	if get("separate") == "1" && len(selected) > 1 {
		h.exportVulnZip(w, selected, format, lang, fnameBase)
		return
	}

	reports := make([]VulnReport, 0, len(selected))
	for _, v := range selected {
		reports = append(reports, buildVulnReport(v, lang))
	}

	if format == "docx" {
		h.exportVulnDOCX(w, reports, lang, fnameBase)
		return
	}
	h.exportVulnPDF(w, reports, lang, fnameBase)
}
